# Generated by Django 5.0.6 on 2024-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.CharField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ', max_length=1000),
        ),
    ]
