# Generated by Django 5.0.6 on 2024-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutexercise_weight_alter_workoutexercise_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
