# Generated by Django 5.0.6 on 2024-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_workout_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_image_url',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
