# Generated by Django 5.0.6 on 2024-05-14 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workout_workout_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
